#! /usr/bin/env python

"""Automatic wrapper around dpkg-source --commit.

See also _commit_editor, which does the editing of the commit.
"""

import sys
import argparse
import os
import os.path
import subprocess
import patcher_config
import glob
import find_source

def main(options):
    """Main program."""
    scripts_dir = os.path.realpath(os.path.dirname(sys.argv[0]))
    config = patcher_config.Config()
    find_source.chdir_source(config)
    for i in ['dch.before', 'dch.after']:
        if os.path.exists(i):
            os.unlink(i)
    for i in glob.glob('gtk/*.orig'):
        os.unlink(i)
    os.environ['XDS_COMMIT_EDITOR_BUILD_INI'] = patcher_config.fullpath()
    editor = os.path.join(scripts_dir, '_commit_editor')
    os.environ['VISUAL'] = os.environ['EDITOR'] = editor
    patch_name = 'xdnd_direct_save_1.patch'
    subprocess.check_call(['dpkg-source', '--commit', '.', patch_name])
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
               description="automatic wrapper around dpkg-source --commit",
             )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
