#! /usr/bin/env python

"""Get the source code from the Ubuntu repositories.
"""

import sys
import argparse
import ConfigParser
import os
import subprocess

def main(options):
    """Main program."""
    config = ConfigParser.RawConfigParser()
    config.read('build.ini')
    source = config.get('package', 'source_package')
    os.mkdir('build')
    os.chdir('build')
    subprocess.call(['apt-get', 'source', source])
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
               description="get the source code from the Ubuntu repos",
             )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
