#! /usr/bin/env python

"""Patch the downloaded source.
"""

import argparse
import os
import os.path
import subprocess
import patcher_config
import find_source
import glob

def main(options):
    """Main program."""
    config = patcher_config.Config()
    patches_dir = config.patches_subdir()
    patches_fullpath = config.patches_fullpath()
    find_source.chdir_source(config)
    patches = glob.glob(os.path.join(patches_fullpath, '*.patch'))
    for patch in sorted(patches):
        basename = os.path.basename(patch)
        print "Applying %s" % (basename)
        with open(patch, 'r') as patchfile:
            subprocess.check_call(['patch', '-p1'], stdin=patchfile)
    return

def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
               description="patch the downloaded gtk+ source",
             )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
