#! /bin/bash

# (C) 2012, Nick Booker
# You need to have installed your custom gtk+ to /tmp/gtk+ first.

export PKG_CONFIG_PATH=/tmp/gtk+/lib/pkgconfig
export LD_LIBRARY_PATH=/tmp/gtk+/lib

gcc `pkg-config --cflags gtk+-3.0` -o example example.c `pkg-config --libs gtk+-3.0`
